- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: rust
  language_version: nightly-2024-05-01
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  language_version: nightly-2024-05-01
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: rust
  language_version: nightly-2024-05-01
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
